### ISSUE TITLE
TypeError: "pageData.items is undefined"

### ISSUE THREAD

**Issue by retostadelmann** [eddex/hslu-simple-mep-results#16]
![grafik](https://user-images.githubusercontent.com/10433328/71713525-5fcc5a00-2e0a-11ea-9cb3-87a84ff148ad.png)

**Comment by eddex** [comment]
Either the [API URL](https://github.com/eddex/hslu-simple-mep-results/blob/7a0546fd501cdc732afef7cca8b20eae921fac96/main.js#L231) has changed or the API itself doesn't return a [list of items](https://github.com/eddex/hslu-simple-mep-results/blob/7a0546fd501cdc732afef7cca8b20eae921fac96/main.js#L241) anymore.

**Comment by eddex** [comment]
Both suggestions in my previous comment are wrong. The request is still the same but if it is sent by our extension, we get the following response: `Object { message: "Authorization has been denied for this request." }`...

**Comment by eddex** [comment]
Update: We couldn't figure out why the API call fails sometimes. Most of the time it works just fine. Might be a timing issue or just HSLU doing HSLU stuff..

Version [2.0.6](https://github.com/eddex/hslu-simple-mep-results/releases/tag/2.0.6) includes error handling for this issue. A message is shown to the user to inform him that the extension failed to download the necessary data.

Workaround: Reload the page.

**Comment by eddex** [comment]
Reopened because this turned out to be a big issue.

After logging in, the requests of our browser add-on get blocked.
We tried the following things to fix it:
- Send the request exactly like the page does (with all headers and properties)
- Reduce the amount of items fetched at the same time
- Wait a few seconds before we send our request
All of the methods above work, if the request is made from the browser console. But in the browser add-on nothing worked.

The only thing that fixes this issue is to stay logged in for 10 - 15 minutes and then reload the page.
Like this, the reuqests from the browser add-on work without problems (no changes in our code needed)

If anyone has an idea on how to fix this, let us know.

**Comment by dev-jan** [comment]
It seems like the session cookie has a new attribute (sameSite=Lax), which only allows the cookie to be send, if the site is the same. As the simple-mep-results plugin runs under another url (something like moz-extension://60a20a9b-1ad4-af49-9b6c-c64c98c37920/, the session will not be passed to the API, as seen in my ZAP proxy screenshot:
![screenshot-mycampus-request](https://user-images.githubusercontent.com/5829661/72829117-6833ea00-3c7e-11ea-9d98-47004157a805.png)


Additionally, the session cookie is newly set in the response, as seen here:
![screenshot-mycampus-error](https://user-images.githubusercontent.com/5829661/72828881-ddeb8600-3c7d-11ea-8a28-303aac201f4d.png)

My merge request should fix this issue (tested with firefox).

**Comment by eddex** [comment]
Thanks @dev-jan! Your pull requests seems to have fixed the issue.

**Comment by eddex** [comment]
Fix got released with 2.0.9! https://github.com/eddex/hslu-simple-mep-results/releases/tag/2.0.9

**Comment by retostadelmann** [comment]
Thank you so much!
