### ISSUE TITLE
Language Courses

### ISSUE THREAD

**Issue by vigi86** [eddex/hslu-simple-mep-results#39]
Sali zäme

Found that the language courses from Sprachzentrum (SZ) aren't recognized as Zusatzmodule yet. 

![image](https://user-images.githubusercontent.com/8401847/73917134-19619380-48bf-11ea-808e-b170a3d79e62.png)
![image](https://user-images.githubusercontent.com/8401847/73917184-30a08100-48bf-11ea-89d8-197aa193d2aa.png)

**Comment by eddex** [comment]
fixed in release [2.0.13](https://github.com/eddex/hslu-simple-mep-results/releases/tag/2.0.13)

The update will be installed automatically.

If you can't wait, you can go to _about:addons_ in Firefox and press "Check for updates".
![image](https://user-images.githubusercontent.com/5302085/74051409-2e7e1580-49d8-11ea-9659-7b21d992acf1.png)
