### ISSUE TITLE
Decimal separator enhancement

### ISSUE THREAD

**Issue by vigi86** [eddex/hslu-simple-mep-results#41]
Little issue in #37 

When typing the grade _"Note"_ with a dot in the manual module mask, the value isn't accepted and saves as zero. Only comma is accepted. 

![image](https://user-images.githubusercontent.com/8401847/73919471-ee2d7300-48c3-11ea-8bce-da9c329d47b9.png)

**Comment by Lextum** [comment]
We could add `<html lang="de">` to the popup.html. With `de` it uses `,` as default, but `.` would still work.

**Comment by eddex** [comment]
fixed in release [2.0.13](https://github.com/eddex/hslu-simple-mep-results/releases/tag/2.0.13)

The update will be installed automatically.

If you can't wait, you can go to _about:addons_ in Firefox and press "Check for updates".
![image](https://user-images.githubusercontent.com/5302085/74051409-2e7e1580-49d8-11ea-9659-7b21d992acf1.png)
