### ISSUE TITLE
Breaking API changes break everything! Grades and Marks have been merged. Everything's broken!

### ISSUE THREAD

**Issue by Lextum** [eddex/hslu-simple-mep-results#72]
~~**What would you like to change?**~~
~~[ Describe the current state and what you want to improve. ]~~
~~Remove the grade from the module table. Reason: HSLU changed every grade value to NULL.
God knows why ;-)~~

~~**Screenshots**~~
~~[ Put images or screenshots to better describe your idea here (if yoiu have some). ]~~

~~**Contributing (please choose one)**~~
~~- [ ]  I'd like to help implementing this change!~~
~~- [ ] I don't have the time to work on this.~~

**Comment by eddex** [comment]
This is not a change request. It's a bug.

**Comment by eddex** [comment]
**Describe the bug**
Right in time for the end of the semester, the API of the MyCampus website has been changed.

Previously there was always a grade (A-F) for all modules and a mark (6-1) for some of them. Now this has been changed. All modules only have a mark filed in the API response. This field contains the mark (6-1) but if there was no mark, it contains the grade (A-F). The grade doesn't just come in form of a single letter but also contains a description in text from.

Example:
![image](https://user-images.githubusercontent.com/5302085/85035868-ef30b400-b183-11ea-9371-df60914fc926.png)
The grade (in the last column) is still in the API response, but it is `null` for all modules.

Known possible values for the marks are:
- 1-6 (numeric)
- bestanden
- B sehr gut
- D befriedigend
- E ausreichend

We need to figure out what the values for grade A, C and F are.

**Expected behavior**
The information displayed by the extension is as expected.

**Actual behavior**

Every module has grade `n/a`:
![image](https://user-images.githubusercontent.com/5302085/85036522-885fca80-b184-11ea-8877-d0231a790827.png)

The grade distribution calculation is broken:
![image](https://user-images.githubusercontent.com/5302085/85036576-97df1380-b184-11ea-9ba1-34af1a843c71.png)

Modules with grade F are counted towards the total resulting in wrong data in the graph:
![image](https://user-images.githubusercontent.com/5302085/85036712-bfce7700-b184-11ea-8522-275fa42e836d.png)


**Steps to Reproduce**
No special steps required, just open the webpage.

**Comment by fafinsch** [comment]
Hi there

I (guess) this was on accident. I'll have to check this internally.
For the time being I reverted the behavior to as it was before.

Kind Regards
Marco

**Comment by Lextum** [comment]
The grades are back, thanks @fafinsch :+1: 
I will close the issue for now.
